CREATE DATABASE IF NOT EXISTS `Rental_Log` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `Rental_Log`;

SET time_zone = '+08:00';

CREATE TABLE IF NOT EXISTS `rental_log` (
    `log_id` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `log_entry_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `log_entry_desc` VARCHAR(255) NOT NULL,
    `vehicle_id` INT(11) NOT NULL,
    `user_id` INT(11) NOT NULL,
    `status` VARCHAR(10) NOT NULL DEFAULT 'CONFIRMED'
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
