_format_version: "1.1"

services:
  - name: carsearch
    url: http://car_search:5100/findNearestCars
    routes:
      - name: SEARCH
        paths:
          - /jomletsgo/searchcar
        methods:
          - POST
          - PUT
          - GET
          - OPTIONS

  - name: report
    url: http://report_damage:5102/create_report
    routes:
      - name: REPORT
        paths:
          - /jomletsgo/reportcar
        methods:
          - POST
          - PUT
          - GET
          - OPTIONS

  - name: cancel
    url: http://report_damage:5102/cancel
    routes:
      - name: CANCEL
        paths:
          - /jomletsgo/cancelcar
        methods:
          - POST
          - PUT
          - GET
          - OPTIONS

  - name: carbook
    url: http://car_booking:5101/car_rental
    routes:
      - name: BOOK
        paths:
          - /jomletsgo/bookcar
        methods:
          - POST
          - PUT
          - GET
          - OPTIONS

  - name: notify
    url: http://notifications:5004/send_notification
    routes:
      - name: NOTIFY
        paths:
          - /jomletsgo/sendnotification
        methods:
          - POST
          - PUT
          - GET
          - OPTIONS

  - name: endtrip
    url: http://car_inventory:5000/end_trip
    routes:
      - name: ENDTRIP
        paths:
          - /jomletsgo/endtrip
        methods:
          - POST
          - PUT
          - GET
          - OPTIONS                        

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      headers:
        - "Access-Control-Allow-Origin"
        - "Content-Type"
      max_age: 3600
